"""Writes the human-readable run report and the auditable suppression file."""

from __future__ import annotations

import json
from pathlib import Path

from bop.stages.context import RunContext


def _q(value: object) -> str:
    """A YAML scalar: JSON strings are valid double-quoted YAML."""
    return json.dumps(value, ensure_ascii=False)


def write_suppressions(ctx: RunContext) -> Path:
    rows = ctx.store.query(
        """SELECT s.*, v.stage, v.model, v.confidence, v.fp_reason, f.start_line, f.end_line
           FROM suppressions s JOIN verdicts v ON v.id = s.verdict_id
           JOIN finding_groups g ON g.id = s.group_id JOIN findings f ON f.id = g.primary_finding_id
           WHERE g.run_id = ? ORDER BY s.id""",
        (ctx.run_id,),
    )
    lines = [
        "# Findings judged not exploitable, with the reasoning an auditor needs.",
        "# Generated by Burden of Proof. Review before merging; every entry cites code that was",
        "# checked against the repository when the verdict was made.",
        "version: 1",
        "suppressions:" + (" []" if not rows else ""),
    ]
    for r in rows:
        evidence = ctx.store.query("SELECT * FROM evidence WHERE verdict_id = ? ORDER BY id", (r["verdict_id"],))
        span = "{}-{}".format(r["start_line"], r["end_line"])
        decided_by = "{} ({}), confidence {:.2f}".format(r["stage"], r["model"], r["confidence"] or 0.0)
        lines += [
            "  - rule: " + _q(r["rule_id"]),
            "    file: " + _q(r["file"]),
            "    lines: " + _q(span),
            "    fingerprint: " + _q(r["fingerprint"]),
            "    reason: " + _q(r["fp_reason"]),
            "    decided_by: " + _q(decided_by),
            "    decided_at: " + _q(r["created_at"]),
            "    justification: " + _q(r["justification"]),
            "    evidence:",
        ]
        for e in evidence:
            at = "{}:{}-{}".format(e["file"], e["start_line"], e["end_line"])
            lines += [
                "      - at: " + _q(at),
                "        code: " + _q(e["excerpt"]),
                "        why: " + _q(e["why"]),
                "        verified: " + ("true" if e["verified"] else "false"),
            ]
    path = ctx.run_dir / "suppressions.yaml"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_report(ctx: RunContext) -> Path:
    store, run_id = ctx.store, ctx.run_id
    run = store.get_run(run_id)
    states = store.group_states(run_id)
    out = [f"# Burden of Proof run {run_id}", ""]
    out += [
        f"- Repository: `{run['repo_path']}`" + (f" at `{run['commit_sha']}`" if run["commit_sha"] else ""),
        f"- Mode: {run['mode']}, status: {run['status']}",
        f"- Spend: ${run['spent_usd']:.4f} of a ${run['budget_usd']:.2f} cap",
        "",
    ]
    out += ["## Outcome", "", "| State | Findings |", "|---|---|"]
    out += [f"| {state} | {n} |" for state, n in sorted(states.items())] + [""]

    groups = store.query(
        """SELECT g.*, f.rule_id, f.file, f.start_line, f.end_line, f.cwe FROM finding_groups g
           JOIN findings f ON f.id = g.primary_finding_id WHERE g.run_id = ? ORDER BY f.file, f.start_line""",
        (run_id,),
    )
    out += ["## Findings", ""]
    for g in groups:
        out += [
            f"### {g['file']}:{g['start_line']} `{g['rule_id']}`",
            "",
            f"- State: **{g['state']}**" + (f" ({g['state_reason']})" if g["state_reason"] else ""),
            f"- Weakness: {g['category']} ({g['cwe'] or 'no CWE'})",
        ]
        for v in store.query("SELECT * FROM verdicts WHERE group_id = ? ORDER BY id", (g["id"],)):
            ok = "evidence verified" if v["evidence_ok"] else "evidence NOT verified"
            out.append(
                f"- {v['stage'].capitalize()} by `{v['model']}`: **{v['verdict']}** "
                f"({v['confidence']:.2f}, {ok}). {v['summary']}"
            )
            if v["taint_path_json"]:
                out.append("  - Path: " + " → ".join(json.loads(v["taint_path_json"])))
        proofs = store.query("SELECT * FROM proof_tests WHERE group_id = ? ORDER BY id", (g["id"],))
        if proofs:
            out.append("- Proof attempts: " + ", ".join(f"{p['attempt']}: {p['outcome']}" for p in proofs))
        patches = store.query("SELECT * FROM patches WHERE group_id = ? ORDER BY id", (g["id"],))
        if patches:
            out.append(
                "- Fix attempts: "
                + ", ".join(f"{p['attempt']}: {'accepted' if p['accepted'] else 'rejected'}" for p in patches)
            )
        fix_diff = ctx.run_dir / "groups" / g["id"] / "fix.diff"
        if fix_diff.is_file():
            out += ["", "```diff", fix_diff.read_text(encoding="utf-8").rstrip(), "```"]
        out.append("")

    out += [
        "## Model routing and cost",
        "",
        "| Model | Stage | Calls | Cached | Prompt tokens | Completion tokens | Reasoning tokens | Cost |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in store.spend_by_model(run_id):
        out.append(
            f"| `{r['model']}` | {r['stage']} | {r['calls']} | {r['cached_calls']} | {r['prompt_tokens']:,} "
            f"| {r['completion_tokens']:,} | {r['reasoning_tokens']:,} | ${r['cost_usd']:.4f} |"
        )
    path = ctx.run_dir / "report.md"
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    return path
